### ISSUE TITLE
making Supermemo anti-aliasing free

### ISSUE THREAD

**Issue by Golddouble** [alessivs/supermemo-wine#15]
In windows I had disabled anti-aliasing.

Now in the wine -version of Supermemo, the GUI is also anti-aliasing free, but in the Items the texts have anti-aliasing.
![Anti-Aliasing in wine](https://user-images.githubusercontent.com/13977359/83066824-f0c7fa00-a065-11ea-8368-8eaee6e9ee8b.png)

How can we disable anti-aliasing in the whole Supermemo? Is there any possibility?

Please note: To see exactly how the picture looks, right click with your mouse on it, choose "save picture". Open it in nomacs. Choose menu->view->disable anti-aliasing. Click the symbol 1:1
Now you see, what I saw.

Thank you.

**Comment by alessivs** [comment]
Unfortunately, I have configured the installers (standalone or not) to enable anti-aliasing in the prefix, as this is the most common case.

Possible ways to disable:

## Disable anti-aliasing for the prefix

You may have already done this.

    Lutris ➞ 
      SuperMemo 17 ➞
        Winetricks ➞
          Select the default prefix ➞ 
            Change settings ➞ 
              [x] fontsmooth=disable

## Use a Wine-only font

**Install a font that only works in the Wine prefix.** Do not install it to `/usr/share/fonts`, `~/.local/share/fonts` or `~/.fonts`, but only through Winetricks.

    Lutris ➞ 
      SuperMemo 17 ➞
        Winetricks ➞
          Select the default prefix ➞ 
            Install a font

You could try with `Tahoma`, which the installer already added to the prefix under the hood, provided you don't have a system Tahoma font, nor a Tahoma font replacement (see below).

**Make sure the font doesn't have an active replacement.** In Debian, `/etc/fonts/local.conf` may define some replacements for non-existing fonts. For example, there `Tahoma` may be bound to `DejaVu Sans`. If so, delete the replacement or try with a different font (see above).

**Use the font in the desired stylesheet**. Set the font as the default text font for the relevant stylesheet, either from the style user (if you have defined a new style) or the global stylesheet (default style).

Custom stylesheet:

    SuperMemo ➞
      Component menu ➞
        Text ➞
           Style ➞
             Edit style

Global stylesheet:

    SuperMemo ➞
      Tools ➞
        Options ➞
          Fonts ➞
            Stylesheet

## Bypass system fontconfig through Lutris

The setting is under:

    Lutris ➞ 
      SuperMemo 17 ➞
        Configure ➞
          System options ➞ 
            [ ] Prefer system libraries

This may have colateral consequences, as I'm not sure if that's all "system libraries" refer to.

**Comment by alessivs** [comment]
Troubleshoot font replacements with `fc-match`. For example, on my Arch system:

```
$ fc-match Tahoma
Vera.ttf: "Bitstream Vera Sans" "Roman"
```

However, inside Wine it works well as the font is properly installed through Wine(tricks).

**Comment by Golddouble** [comment]
```
Lutris ➞ 
  SuperMemo 17 ➞
    Winetricks ➞
      Select the default prefix ➞ 
        Change settings ➞ 
          [x] fontsmooth=disable
```
Done.
-> Result: Has no effect.

> Use a Wine-only font

I have **not** done this until now. Why is this necessary?
Most of my texts are in Arial. Until now wine uses this font from "/usr/share/fonts", because I have deleted Arial in the Lutis-wine-prefix. (Just, not to have it double times.)

This is my "/etc/fonts/local.conf":
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <alias>
    <family>sans-serif</family>
    <prefer><family>Tahoma</family></prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer><family>DotumChe</family></prefer>
  </alias>
  <alias>  
  <family>serif</family>
    <prefer><family>Times New Roman</family></prefer>
  </alias>
   <match target="font">
    <edit mode="assign" name="antialias">
       <bool>false</bool>
    </edit>
   </match>
  </fontconfig>
```

> Bypass system fontconfig through Lutris

-> Result: This has no effect on anti-aliasing, but it slows down the SM start.

```
$ fc-match Arial
arial.ttf: "Arial" "Standard"
```

**Comment by alessivs** [comment]
Alright. Seems that fontconfig smoothing is inescapable so far. Sorry for the time-waste. 

I remembered Internet Explorer has its own font smoothing setting.

```
Lutris ➞
  SuperMemo 17 ➞
    Run EXE inside wine prefix ➞ prefix/drive_c/Program Files/Internet Explorer/iexplore.exe
      Tools ➞
        Internet Options ➞
          Advanced ➞
             Multimedia: [ ] Always use ClearType for HTML
```

Then close everything in the prefix, give it time for the Wine processes to terminate, and restart SuperMemo.

**Comment by Golddouble** [comment]
> Sorry for the time-waste.

No problem.

Thank you. Successful. I like it. :-)
