### ISSUE TITLE
Internet Explorer and windows managing

### ISSUE THREAD

**Issue by doesn123** [alessivs/supermemo-wine#26]
As for use of IE with SM - I've managed to open it with:  WINEPREFIX=~/.local/share/wineprefixes/supermemo18 wine ~/.local/share/wineprefixes/supermemo18/drive_c/Program\ Files/Internet\ Explorer/iexplore.exe
I read that you can't do mass imports, or have a running instance of IE - in that case: how do you use in conjunction with SM?

With regards to windows managing - I imagine it takes some experimentation to find what windows setting (under winecfg/Graphics) works depending on the WM/DEs used - but if you have general advice, that'd be helpful - I haven't found setting that allow me to be able to switch between tags (alt+tab) in dwm that's worked yet - perhaps you know of a specific patch that can help?

Thanks again!

**Comment by alessivs** [comment]
> I read that you can't do mass imports

Nope. It depends on system calls that, last time I looked, are implemented in Wine maybe about 40%. I need an updated look to be more precise.

> or have a running instance of IE

Of course you can. It used to be the case you couldn't start standalone iexplore.exe but winetricks fixed that long ago.

> how do you use in conjunction with SM?

Copy-paste, both manually and automated. I use a native browser (any, but webkit (e.g. webkitGTK, qtwebengine), and by extension Chromium, requires filtering some styles with F6 after import). I barely use iexplore. You have *nix tools at your disposal!

> I haven't found setting that allow me to be able to switch between tags (alt+tab) in dwm that's worked yet 

SM 18 removed a feature named Next window (*Window : Select : Next Window (Ctrl+F6)*) that switched among SM windows (except *Ancestors* for some reason). I feel it had something to do with removal of the dock.

Eventually you could patch this into dwm. I haven't done that and I don't think I'll have a chance to look at the docs, so I can't give you guidance right now. Under X11 every window has an ID, a class name and maybe a differentiating title. These are all queryable. You could keep a stack data structure in dwm and implement history functionality, or direct focusing with dmenu, etc. With multi-window SuperMemo it would be somewhat straightforward. With desktop window you have a changing hierarchy of windows with more guessing to do. I used to have the latter setup with EXWM (a WM inside Emacs), but no longer.

**Comment by alessivs** [comment]
Feel free to reopen with new information or requests.
