### ISSUE TITLE
Incremental Video and PDF functionality

### ISSUE THREAD

**Issue by doesn123** [alessivs/supermemo-wine#27]
Hi there,

Do you have any experience setting up Incremental Video and PDF functionality with SuperMemo Wine?
I've heard its possible with help of the Emacs package [org-noter](https://github.com/weirdNox/org-noter) for PDF and [org-media-note](https://github.com/yuchen-lea/org-media-note), mpv and IPV handlers for Incremental Video.
On the Emacs side it should be straight forward but I wouldn't know what to do on the SuperMemo end.

I would love to set this up and any help would be greatly appreciated!

**Comment by alessivs** [comment]
org-noter is good. I rely on it for documents that have text layers (OCRed or digitally produced). You can write an elisp macro to automate pasting to SuperMemo (or at least put stuff into the clipboard); or accumulate clipboard captures witht CopyQ, then dump all at once into SM. Or if you prefer Zathura you can script it as well (I recommend the mupdf backend). I've already planned documenting some of these paths.

As for video, I haven't explored enough, though I remain receptive to others' recommendations. It's hard to find videos which don't involve huge wastes of time to extract little value; more so in the influencer, product-shill, content-free age. I don't have a huge motivator to explore further.

**Comment by doesn123** [comment]
I'll be going down the org-noter, elisp scripts and clipboard route for PDF
Thanks!

**Comment by doesn123** [comment]
Do you know of way for SM to programmatically open a PDF in an emacs buffer when the topic associated to that PDF is selected? I found a lot of value in having this PDF support with SMA (SuperMemo Assistant).

It's that initial link between SM and emacs that I don't know how to establish.

**Comment by alessivs** [comment]
On 12/06/2021 14:09, doesn123 wrote:
> Do you know of way for SM to programmatically open a PDF in an emacs
> buffer when the topic associated to that PDF is selected?
> 

This is achievable with file associations and hyperlinks, in conjunction
with `org-protocol`, or SuperMemo scripts that play at browse time. Like
everything else, it's not available out of the box. Feel free to
explore; I need to gather notes and do further testing before I get to
document it. For me, updating the installers and moving this project has
more priority right now; documentation is next.

**Comment by doesn123** [comment]
OK, thanks alessivs!
