### ISSUE TITLE
URL of file needed for install returns 404 error -> Install fails

### ISSUE THREAD

**Issue by mystiquewolf** [alessivs/supermemo-wine#34]
# Platform information

## Name of checkout or release of supermemo-wine used

SuperMemo 15.4 verb.

## Output of `uname -rom`

`5.15.13-zen1-1-zen x86_64 GNU/Linux`

## Output of `wine --version`

`wine-7.0-rc5 (Staging)`

## Output of `winetricks --version`

`20210206-next`

# Problem Description

```
Downloading https://ftp.hp.com/pub/softlib/software/msi/InstMsiW.exe to /home/wineuser/.cache/winetricks/msls31
warning: sha256sum mismatch! Rename /home/wineuser/.cache/winetricks/msls31/InstMsiW.exe and try again. Alternatively, use --force to ignore this check.
```
Notice that the URL returns 404 and `file` gives `/home/wineuser/.cache/winetricks/msls31/InstMsiW.exe: HTML document, ASCII text`

**Comment by alessivs** [comment]
You may be using a known VPN service, or otherwise identifiable/blockable IP? That hp mirror has been known to reject certain IP ranges. Retry from a different IP if you can.

In any case, the source of the problem is the `ie8` winetricks verb. You can isolate this problem with the following invocation:

```sh
WINEPREFIX="/choose/your/prefix/path" WINEARCH=win32 winetricks ie8
```

... and if you can reliably reproduce the problem from a non-blocked IP, it should be reported to Winetricks/winetricks

**Comment by mystiquewolf** [comment]
Could you please check if that you can successfully download a DOS executable file? I'm using a private home landline network and get 404 with Firefox, with curl i get the file called .exe but it is just the HTML file with the 404 error page, albeit named as an .exe file.

I also tried with one Google Cloud VM Instance and with my phone, which is a different ISP provider and everything is the same.

Isn't there a more stable working URL with which the script can be updated?

**Comment by mystiquewolf** [comment]
Nevermind, found out that this is about to be fixed: https://github.com/Winetricks/winetricks/commit/078e74b428c84baef07717acc9ecafb0a5b6aa66#diff-0120b8c6219f57131e91b23416142b37b990b95acb666919ec3db84d4e410c4aL11251
