### ISSUE TITLE
SM17: HTML Component: Assigning a font does not work

### ISSUE THREAD

**Issue by Golddouble** [alessivs/supermemo-wine#9]
Please have a look at the Gif-Animation.
![SM17 link font](https://user-images.githubusercontent.com/13977359/79615366-e0d20780-8102-11ea-830e-3c2fbf4538e6.gif)

**Comment by alessivs** [comment]
Confirmed. Good catch. Will get back to you.

**Comment by alessivs** [comment]
Right after failing to apply the font, what is the produced HTML code?

**Comment by Golddouble** [comment]
I made it again now with a new Item and "abc def". Trying to make def "red":

Ctrl+Shift+F6 before:
`abc def`

Ctrl+Shift+F6 after:
`abc def`

No change. No effect.

**Comment by alessivs** [comment]
**Observation**. I reproduced this on more than one version of Wine (4.9 to 5.2) for SuperMemo 17 and 18, but it is not consistent. When the issue presents on a given font registry member, it persists for the lifetime of that font registry member. It does not relate to either the naming of the font registry member, the font size used, nor whether the font name has spaces in it. I did not debug it further.

**Workaround**. Delete the problematic font registry member (changes to fonts don't propagate or get automatically linked to templates, so it is safe). Then, produce another font registry member of similar characteristics and repeat the font linking process using the new font.

**Comment by Golddouble** [comment]
Thank you for reproducing this. In the meantime I have created a lot new font registry members. None of them works.
OK. It's just a limit of the wine-version we have to live with.

**Comment by alessivs** [comment]
I think it can be salvaged and there's a way out. In my case it was a sort of intermittent or erratic bug, contained within a given font registry member. Creation of a new one had a high chance of not causing the misbehavior.

For now I'll leave this issue open until I can further debug this. (BTW I am prioritizing #3, which might interest you)

**Comment by alessivs** [comment]
Closing until not proven intermittent or without a way out.
